{% set DATA = load_setup_py_data() %}
{% set BRANCH = 'develop' %}
{% set OTHER_PACKAGES_REQUIRED_VERSION = '=='+GIT_DESCRIBE_TAG if BRANCH=='master' else '' %}

package:
    name: simulation
    version: {{ DATA.get('version')}}

source:
    git_url: https://github.com/jor-/simulation
    git_rev: {{ BRANCH }}

build:
    number: 0
    noarch: python

requirements:
    build:
        - git
    host:
        - python >=3.6
        - setuptools >=0.8
        - pip >=10
    run:
        - python >=3.6
        - numpy
        - scipy
        - utillib {{ OTHER_PACKAGES_REQUIRED_VERSION }}
        - measurements {{ OTHER_PACKAGES_REQUIRED_VERSION }}
        - matrix-decomposition >=1.1

about:
    home: {{ DATA.get('url') }}
    summary: {{ DATA.get('description') }}
    license: {{ DATA.get('license') }}
    license_family: {{ DATA.get('license') }}
    license_file: LICENSE.txt

extra:
    maintainers:
        - {{ DATA.get('author') }}
