package:
  name: simulation
  version: "0.1.1.dev80"

source:
  fn: simulation-0.1.1.dev80.tar.gz
  url: https://pypi.python.org/packages/43/82/abe92f5fd27527b4d05f56445ae2987f1d108918a090b69f8531792aea27/simulation-0.1.1.dev80.tar.gz
  md5: 9b37dbc08a0cc063a0d08b2e07be0af1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - simulation = simulation:main
    #
    # Would create an entry point called simulation that calls simulation.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - setuptools
    - setuptools_scm
    - python
    - numpy
    - scipy
    - utillib
    - measurements

  run:
    - python
    - numpy
    - scipy
    - utillib
    - measurements

test:
  # Python imports
  imports:
    - simulation
    - simulation.accuracy
    - simulation.model
    - simulation.oed
    - simulation.optimization
    - simulation.optimization.matlab
    - simulation.plot

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jor-/measurements
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'simulation functions'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
